config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients
  resources :doctors
  resources :logins
  resource  :doctor, :controller => :doctors, :only => :show

  root 'logins#new'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	has_many :patients
	validates :doctorname, presence: true, uniqueness: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :doctor
	validates :name, :phone_number, :doctor_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  before_action :authenticate_user!
	def new
	@doctor =Doctor.new
	end

	def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
    redirect_to doctors_path(doctor_params[:id])
    flash[:notice] = "successful"
  else
    redirect_to new_doctor_path
    flash[:error] = "unsuccessful!!"
  end
end

  def index
    @doctors = Doctor.all
  end
  
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end
  
  def show
    @doctor = Doctor.find(params[:id])
  end

  private

    def doctor_params 
      params.require(:doctor).permit(:doctorname, :gender, :email, :specialization, :ph_number, :experience)
    end



end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new
	end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def new
		@patient = Patient.new
end

def create
    @patient = Patient.new(patient_params)
    #puts patient_params
    if @patient.save
    redirect_to patients_path(patient_params[:id])
    flash[:notice] = "successful"
  else
    redirect_to new_patient_path
    flash[:error] = "unsuccessful"
  end
end

  def index
    @patients = Patient.all

  end

  def show
  @patient = Patient.find(params[:id])
  end


  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path
  end

  def edit
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :phone_number, :doctor_id, :address, :reasons)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/index.html.erb
<h1> Showing Doctors </h1>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %> </div>
<% end %>

<table style="border: 1px solid black;">
	<tr>
		<th> Name </th>
		<th> gender </th>
		<th> email </th>
		<th> specialization </th>
		<th> ph_number </th>
		<th> experience </th>
		<th> Actiond# </th>
		<th> Action </th>
	</tr>

	<% @doctors.each do |d| %>
	
	<tr>
		<td><%= d.doctorname %></td>
		<td><%= d.gender %></td>
		<td> <%= d.email %></td>
		<td><%= d.specialization %></td>
		<td><%= d.ph_number %></td>
		<td><%= d.experience %></td>
		<td style="text-align: center;"> <%= Patient.where(:doctor_id => d.id).count %></td>
	    <td><%= link_to "Delete", doctor_path(d), method: :delete, data: { confirm: "Are you sure!" } %></td>
	    <td><%= link_to "show", doctor_path(d) %></td>
	</tr>
	<% end %>
</table>

<style>
.notice{
	color:#3ABf00;
}
h1
{
	position: relative;
	top: 25%;
	left: 35%;
	right: 45%;
	color: violet;

}
</style>
<td><%= link_to "new", new_doctor_path %></td>
<td><%= link_to "home", new_login_path %></td>

app/views/doctors/new.html.erb
<h1> Doctors login page </h1>
<% if flash[:error] %>
<div class="error"><%= flash[:error] %> </div>
<% end %>
<%= form_for @doctor do |f| %>
<table>
	<tr>
		<td>  Name </td>
		<td> <%= f.text_field :doctorname %> </td>
	</tr>
	<tr>
		<td>  Gender </td>
		<td> <%= f.radio_button 'gender', 'Male' %> Male
		<%= f.radio_button 'gender', 'Female' %> Female </td>
	</tr>
	<tr>
		<td>  Email </td>
		<td> <%= f.text_field :email %> </td>
	</tr>
	<tr>
		<td>  Specialization </td>
		<td> <%= f.text_field :specialization %> </td>
	</tr>
	<tr>
		<td>  Ph_number </td>
		<td> <%= f.number_field :ph_number %> </td>
	</tr>
	<tr>
		<td>  Experience </td>
		<td> <%= f.number_field :experience %> </td>
	</tr>
</table>
<%= f.submit %>
<% end %>

<style>
.error{
	color: #ff0000;
}

app/views/doctors/show.html.erb
<h1>showing Doctors information</h1>
<% @no_patients = Patient.where(:doctor_id => @doctor.id) %>
<p>
  <strong>Name:</strong>
  <%= @doctor.doctorname %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @doctor.gender %>
</p>
<p>
  <strong>Email:</strong>
  <%= @doctor.email %>
</p>
<p>
  <strong>Secialization:</strong>
  <%= @doctor.specialization %>
</p>
<p>
  <strong>Ph_number:</strong>
  <%= @doctor.ph_number %>
</p>
<p>
  <strong>Experience:</strong>
  <%= @doctor.experience %>
</p>
<p>
  <strong>Assigned:</strong>
  <%= @no_patients.count %>
</p>
<p>
  <strong>Assigned Patient name:</strong>
  <%i =0%> 
  <% @no_patients.each do |p| %>
  <%i+=1%>
  <p> <%= "#{i}"+". " + p.name %></p>

 <% end %>
</p>
<%= link_to "index", patients_path %>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to "new patient", new_patient_path %>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>FacebookAuthTest</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <%= render 'layouts/user_widget' %>
  

</body>
</html>

app/views/logins/new.html.erb
<h1> Welcome</h1>

<style>
h1
{
	color: magenta;
}
</style>

app/views/patients/index.html.erb
<style>
.notice{
	color:#3ABf00;
}
h1
{
	position: relative;
	top: 25%;
	left: 35%;
	right: 45%;
	color: orange;

}
body {
	background-image: url('/assets/925104020-6147010-1_s.jpg')
}

</style>
<h1> Patient form </h1>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %> </div>
<% end %>
<table>
	<tr>
		<th> Name </th>
		<th> Phone_number </th>
		<th> Address </th>
		<th> Reasons </th>
		<th> Doctor </th>
		<th> Action </th>
	</tr>
	<% @patients.each do |p| %>
	<% @doc = Doctor.where(:id=>p.doctor_id).first.doctorname %>
	<tr>
		<td><%= p.name %></td>
		<td><%= p.phone_number %></td>
		<td><%= p.address %></td>
		<td><%= p.reasons %></td>
		<td><%= !@doc.nil? ? @doc :'nill' %></td>
		<td><%= link_to "show", patient_path(p) %></td>
	<td><%= link_to "Delete", patient_path(p), method: :delete, data: { confirm: "Are you sure!" } %></td>
	

	</tr>
	<% end %>
</table>

<td><%= link_to "new", new_patient_path %></td>
<td><%= link_to "home", new_login_path %></td>

app/views/patients/new.html.erb
<h1> Patient login page </h1>
<% if flash[:error] %>
<div class="error"><%= flash[:error] %> </div>
<% end %>
<%= form_for @patient do |f| %>
<table>
	<tr>
		<td> Name </td>
		<td><%= f.text_field :name %></td>
	</tr>

	<tr>
		<td> Phone_number </td>
		<td><%= f.number_field :phone_number %></td>
	</tr>

	<tr>
		
		<td><%= f.label :doctor %><br /></td>
		<td><%= collection_select(:patient, :doctor_id, Doctor.all, :id, :doctorname)  %> </td>
		
	</tr>

	<tr>
		<td> Address </td>
		<td><%= f.text_area :address %></td>
	</tr>

	<tr>
		<td> Reasons </td>
		<td><%= f.text_field :reasons %></td>
	</tr>
</table>
<%= f.submit %>
<% end %>
<style>
.error{
	color: #ff0000;
}	
</style>
<%= link_to "index", patients_path %>

app/views/patients/show.html.erb
<h1>showing patient information</h1>
<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Phone_number:</strong>
  <%= @patient.phone_number %>
</p>

<p>
<strong>Doctorname</strong>
<% @doc=Doctor.where(:id=>@patient.doctor_id).first.doctorname %>
<%= !@doc.nil? ? @doc :'nill' %>
</p>
<%= link_to 'Back', patients_path %>